[package]
name = "nebula-fbthrift-meta"
version = "0.2.0"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2018"
description = "Nebula Graph meta interface"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/bk-rs/nebula-rs"
homepage = "https://github.com/bk-rs/nebula-rs"
documentation = "https://docs.rs/nebula-fbthrift-meta"
keywords = []
categories = []
readme = "README.md"

[dependencies]
fbthrift = { package = "fbthrift-git", version = "=0.0.6", default-features = false }

anyhow = { version = "1.0", default-features = false }
futures = { version = "0.3", default-features = false, features = ["std"] }
async-trait = { version = "0.1", default-features = false }
const-cstr = "0.3"

common = { path = "../nebula-fbthrift-common", package = "nebula-fbthrift-common", version = "=0.2.0", default-features = false }
